
CREATE TABLE absent_records (
    id SERIAL PRIMARY KEY,
    student_id INTEGER NOT NULL,
    details JSONB NOT NULL,
-- approved_status BOOLEAN DEFAULT false NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE absent_records ADD COLUMN "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE absent_records ADD COLUMN "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP;